[variables]
NPM_CONFIG_PRODUCTION = 'false'
NODE_ENV = 'production'

[phases.install]
cmds = ['npm install --include=dev']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npx serve -s dist -l ${PORT:-3000}'
